authors = ["Atai Akunov <aakunov@bankofcanada.ca>", "Boyan Bejanov <bbejanov@bankofcanada.ca>", "Nicholas Labelle St-Pierre <labs@bankofcanada.ca>"]
name = "ModelBaseEcon"
uuid = "1d16192e-b65e-11ea-11ed-0789cee22d2f"
version = "0.1.0"

[deps]
